INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Ferrari', 'Italia');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Red Bull Racing', 'Austria');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Mercedes AMG', 'Alemania');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('McLaren', 'Reino Unido');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Aston Martin', 'Reino Unido');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Alpine F1 Team', 'Francia');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Williams Racing', 'Reino Unido');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Hass', 'EE.UU.');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Racing Bull', 'Italia');
INSERT INTO `#__escuderias` (`nombre`, `pais`) VALUES ('Audi', 'Audi');

INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Charles', 'Leclerc', 1, '1997-10-13', '2018-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Carlos', 'Sainz', 1, '1994-03-01', '2015-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Max', 'Verstappen', 2, '1997-09-30', '2015-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Sergio', 'Pérez', 2, '1990-01-26', '2015-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Lewis', 'Hamilton', 3, '1985-01-07', '2007-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('George', 'Russell', 3, '1998-02-15', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Lando', 'Norris', 4, '1995-11-13', '2019-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Daniel', 'Ricciardo', 4, '1989-07-01', '2014-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Sebastian', 'Vettel', 5, '1983-07-03', '2006-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Lance', 'Stroll', 5, '1998-10-29', '2020-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Fernando', 'Alonso', 6, '1985-07-29', '2006-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Esteban', 'Ocon', 6, '1996-09-16', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Alex', 'Albon', 7, '1996-03-23', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Nicholas', 'Latifi', 7, '1995-06-04', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Mick', 'Schumacher', 8, '1997-03-22', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Kevin', 'Magnussen', 8, '1988-10-05', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Pierre', 'Gasly', 9, '1996-02-07', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Yuki', 'Tsunoda', 9, '2000-05-11', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Sebastian', 'Bourdais', 10, '1988-06-13', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('Romain', 'Grosjean', 10, '1985-09-29', '2022-01-01');
INSERT INTO `#__pilotos` (`nombre`, `apellido`, `id_escuderia`, `fecha_nacimiento`, `fecha_incorporacion`) VALUES ('René', 'Rast', 11, '1994-05-27', '2022-01-01');